# M05 NumPy

## Topics

-   Numpy and its role in the Python data science ecosystem
-   Numpy Arrays
-   Array indexing, slicing, and broadcasting
-   Aggregation
-   Timing the difference between NumPy and plain old Python

## Readings

### Required

-   [McKinney 2023, Chapter 4: Numpy Basics](https://wesmckinney.com/book/numpy-basics)

### Optional

-   [McKinney 2023, Appendix A. Advanced NumPy: A.3 Broadcasting](https://wesmckinney.com/book/advanced-numpy#numpy_broadcasting)
-   [NumPy for Beginners (Official)](https://numpy.org/doc/stable/user/absolute_beginners.html)

## Videos

<iframe src="https://kaltura-connect.its.virginia.edu/embedplaylist/secure/embed/v2/1/playlistId/1_zcuqcvm2/uiConfId/44972551" width="740px" height="330px" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerpolicy="no-referrer-when-downgrade" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="M01 Introducing Python"></iframe>